### ISSUE TITLE
Extract CSS

### ISSUE THREAD

**Issue by aaaxx** [buzz/imdb-link-em-all#12]
The current bunch of concatenated strings makes the CSS pretty painful to edit. And looking at the [formatted code](https://gist.github.com/aaaxx/fa05421656cd4c020ad0705b2fd00bf9), adding another hundred lines of code in a template literal to the already long script doesn't seem that great either.

Could you extract it to a separate file?

**Comment by aaaxx** [comment]
I played around with this a bit, and although they dropped `GM_getResourceText` in Greasemonkey 4+, [this seems to work](https://wiki.greasespot.net/GM.getResourceUrl), using the `<link rel="stylesheet" href="url.css"/>` element instead of `<style type="text/css">...</style>`.

Since I only dabble in programming, I don't want to send a PR, in case I messed something up.

**Comment by aaaxx** [comment]
Yeah, the absolute link to the raw GitHub file is what I had in mind.

**Comment by buzz** [comment]
Will look into that at some point. Can't say when that is going to be.

If you want to test and create a PR, go for it!
