### ISSUE TITLE
addic7ed Fix

### ISSUE THREAD

**Issue by alpcinar** [buzz/imdb-link-em-all#29]
They recently updated their search page url. 
search.php -> srch.php

Old:
`http://www.addic7ed.com/search.php?search={{IMDB_TITLE}}&Submit=Search`

New:
`http://www.addic7ed.com/srch.php?search={{IMDB_TITLE}}&Submit=Search`

**Comment by buzz** [comment]
> Old:
> `http://www.addic7ed.com/search.php?search={{IMDB_TITLE}}&Submit=Search`

Can't confirm. `search.php` works perfectly fine here...

**Comment by Theo47** [comment]
My bad. I just went with the info on this issue and didn't actually test it.
