### ISSUE TITLE
Multiple strings in results matcher

### ISSUE THREAD

**Issue by aaaxx** [buzz/imdb-link-em-all#3]
If this is possible, Zooqle has two cases for no results. They seem to have some kind of internal database of films, and give different responses for no results depending on whether the film is in their database or not.

- https://www.imdb.com/title/tt0000001/ `Sorry, no torrents match your query`
- https://www.imdb.com/title/tt6793280/ `Sorry, we haven't matched torrents for this movie yet. Come back later!`

**Comment by buzz** [comment]
In this case it's possible to match against the string `Sorry, ` because it works in both cases.

The parameter can also be a function (needs to return `true` for available results). Look at `podnapisi` for an example:

```javascript
function($dom) {
  return $dom.find('table.table tr.subtitle-entry').length > 0;
}
```
