### ISSUE TITLE
Site to be added

### ISSUE THREAD

**Issue by morrinson** [buzz/imdb-link-em-all#37]
Could you please add the site www.senscritique.com (https://www.senscritique.com/search?q=search&categories[0][0]=Films) for frenchies?
Many thanks.

PS: I'm using an old modified version but I cannot tweak it anymore due to an error "404 - Not Found https://raw.githubusercontent.com/buzz/imdb-link-em-all/master/style.css" when I try to save the script.

**Comment by buzz** [comment]
Always use the current version. 

Added in 547b11efd6216bac5da1bea5b75f0b9e3640b6f3.

**Comment by morrinson** [comment]
Many thanks for your fast update!

I used to keep an old version because I liked to modify some links / add websites nobody else is interested in / change the search scheme, but it doesn't seem to be possible with the most recent version — since  v2.0.1 actually.
Am I wrong, and is it intentional?

Thanks again.

**Comment by buzz** [comment]
> I used to keep an old version because I liked to modify some links / add websites nobody else is interested in / change the search scheme, but it doesn't seem to be possible with the most recent version — since v2.0.1 actually.
> Am I wrong, and is it intentional?

It's being worked on: #34

**Comment by morrinson** [comment]
Many thanks for your work.
