### ISSUE TITLE
Not compatible with the new IMDb layout

### ISSUE THREAD

**Issue by alpcinar** [buzz/imdb-link-em-all#38]
Just got a banner notification saying "Get a sneak peek of the new version of this page." on title pages and the script is not working on the new version.

Example link: https://www.imdb.com/preferences/beta-control?e=tmd&t=in&u=/title/tt5727208/&ref_=tt_optin_banner

**Comment by buzz** [comment]
Thanks for reporting the new layout. For now, I will not invest much time in the polishing of styles though as the design is likely to change again.

I will leave this comment open for future updates on the beta redesign.

**Comment by V-Toll** [comment]
It worked for a few months with the new design but seems broken now (Google Chrome on macOS with Tampermonkey, all up to date).

**Comment by buzz** [comment]
The script will be updated to the new layout once it becomes the default. I rather invest development time in other useful features than in a constantly changing beta layout.

**Comment by mimteatr** [comment]
I understand,  except that is no longer beta, now it is official, the old layout with beta option is not available anymore.

**Comment by buzz** [comment]
> I understand, except that is no longer beta, now it is official, the old layout with beta option is not available anymore.

Interesting. Do you have a source for this claim?

Here it's still showing the old layout. I didn't even receive one of the beta opt-in banners until today. Big websites like IMDb sometimes do rollouts in phases, meaning part of the userbase is still seeing the old layout. I may also be that you permantly opted-in to the new layout, so it seems that the new layout became the default. Could you check with another browser or a clean browser profile?

@mimteatr On another note, would you consider taking back the negative rating on the userscript at Greasyfork?
https://greasyfork.org/en/scripts/17154-imdb-link-em-all/discussions/87702
I find it kind of harsh to vote down the script. I devote a lot of unpaid sparetime to this project and constantly maintain it over many years now. My motivation slider for keeping up the work diminishes with every negative review.

**Comment by buzz** [comment]
Fixed in 92c8c117e707c659fcbd02bfa69760095006c24c
