### ISSUE TITLE
Language choice for OS

### ISSUE THREAD

**Issue by wjk82** [buzz/imdb-link-em-all#39]
Hello!

Is there a possibility to select a multiple language of search results in OpenSubtitles? The default search is ENG but it would be very helpful if this extension could add multiple languages to one search, or multiple OepenSubtitles buttons to each selected language separatly?

Keep up good work!

**Comment by buzz** [comment]
I'm currently extending the script, so that you can add/edit custom entries (and also share them with the community).
It's a bigger change, so no ETA.

**Comment by wjk82** [comment]
Sounds good, that will be very useful indeed.
