### ISSUE TITLE
Wikipedia links to wrong article

### ISSUE THREAD

**Issue by leodoi3** [buzz/imdb-link-em-all#40]
If there are several movies with a same name , the Wikipedia link would not match the correct title.  Or if a movie is based on a book, sometimes it links to the book article.
I tried it with [I, Robot (2004)](https://www.imdb.com/title/tt0343818/) , and the Wikipedia link takes me to the book.

**Comment by buzz** [comment]
IMDb Link'em all just takes you to the standard Wikipedia search page, using the movie title as search term.
If the title happens to exactly match an article name, Wikipedia redirects you directly to that article (This is what happens in case of I, Robot). That's just how the Wikipedia search works.

Ideally Wikipedia would allow to search for an IMDb ID and take you to the films article, but this is not the case.

To improve this, one could experiment to construct a better Wikipedia search query:

1. You could fiddle with advanced search page and try to construct a search that only includes films. Still this would be imperfect as IMDb entries are not always films, also TV shows, mini series, games, ....  
  So, you would need to determine the type of an IMDb entry first (see #8) to construct better search queries. But this might become too complex. You would need a way to construct different queries for each supported website depending on the IMDb entry type.
2. Append another search term, e.g. "film" or the movie release year ("2004") to the title to prevent Wikipedia from redirecting you to the article.

**Comment by leodoi3** [comment]
Is it possible to add an option to modify the search query?  Probably to append the year to it. 
When a movie has a remake: [Pet Sematary  (1989)](https://www.imdb.com/title/tt0098084/) and [Pet Sematary (2019)](https://www.imdb.com/title/tt0837563/) . Both of them are based on a book , and lead to the same article.

**Comment by buzz** [comment]
That is being implemented and will be possible in a future version. #34 #36

**Comment by leodoi3** [comment]
One suggestion you can do is use the [External links search](https://en.wikipedia.org/w/index.php?target=&title=Special%3ALinkSearch&title=Special%3ALinkSearch) tool. And search for a link i.e https://www.imdb.com/title/tt0111161 and match it with the correct title.
