### ISSUE TITLE
Sites don't show on new layout 

### ISSUE THREAD

**Issue by leodoi3** [buzz/imdb-link-em-all#50]
On the new IMDB layout , sometimes the layout does not show , or I only see the cog icon. 

https://www.imdb.com/title/tt0438488/

![image](https://user-images.githubusercontent.com/46114199/124677715-e46fbc80-de75-11eb-8d79-908ffb209e66.png)

**Comment by arogl** [comment]
Seeing similar issues in MSEdge DEV (win10 fully patch 21H1)and Tampermonkey (v2.13.0), and scripts updated manually to ensure the latest version.

**Comment by buzz** [comment]
I can confirm this bug. I think there's a race condition. Elements that are drawn dynamically by the page are not available when the script injects its HTML. Solution is to wait until the elements are available on page.

**Comment by buzz** [comment]
I can't reproduce this issue anymore. Does anyone still have this?
Nevertheless I moved the container element for the injection which might improve the situation.

**Comment by buzz** [comment]
v2.0.9 is out which hopefully remedies the issue. Please report back if it works.

**Comment by leodoi3** [comment]
Seems to be working now , thanks! I will update if it reoccurs.

**Comment by buzz** [comment]
Closing for now. Please re-open if this bug appears again.
