### ISSUE TITLE
Not working one more time

### ISSUE THREAD

**Issue by davix004** [buzz/imdb-link-em-all#58]
One more time, the script is not working. I'm using Firefox 96.0. Windows 10 1803 x64. It's not working with Tampermonkey 4.13.6136 nor with Greasemonkey 4.11. I try uninstalling and reinstalling the script, with uninstalling and reinstalling the extensions, try with a new Firefox profile, the script continues to not work at all.
The errors that I detect are:

With Greasemonkey:
Source map error: Error: URL constructor: hooks.umd.js.map is not a valid URL.
Resource URL: user-script:https%3A//greasyfork.org/en/users/8981-buzz/IMDb%3A%20Link%20%27em%20all%21
Source Map URL: hooks.umd.js.map

With Tampermonkey:
Uncaught Error: LTA: Could not find target container!
And
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://3ad31524-7c0b-47c9-af8c-dfa6c131655b/userscripts/IMDb%3A%20Link%20'em%20all!.user.js?id=0ef2934f-3bb9-4a55-aec3-b848adba6f45
Source Map URL: hooks.umd.js.map

I also tried with disabled firewall, VPN, changing my IP, still without being able to make the script work.

Maybe IMDB has changed one more time the site layout...

**Comment by buzz** [comment]
IMDb changed the layout again. v2.0.12 should fix it.
