### ISSUE TITLE
CringeMDB support?

### ISSUE THREAD

**Issue by v0iden** [buzz/imdb-link-em-all#61]
CringeMDB is a website that displays information on whether a movie is family friendly or not. It is based on TMDB and community maintained. Would this be possible to add to the extension?

Here's an example: https://cringemdb.com/movie/oldboy-2013

**Comment by buzz** [comment]
CringeMDB doesn't expose the search through a regular POST or GET request but relies on an [API](https://cringemdb.com/search?term=test). We would need to implement #9 first to make it work.

**Comment by v0iden** [comment]
can't you just generate a URL and hope it is listed on cmdb?

**Comment by buzz** [comment]
Well, you would somehow need to go from the fields parsed from the IMDb page (title, year) to a working CringeMDB URL, e.g.
title=`oldboy` year=`2013` ⟶ `https://cringemdb.com/movie/oldboy-2013`

To be able to do this in a reliable and flexible way, you'd want some rule based text transforms, I suppose. They seem to replace special characters and blanks with dashes, etc. **PR welcome!**

Before heading down that road it might be better to go with a fancy descriptive API adapter for the true search functionality.

**Comment by buzz** [comment]
Closed due to inactivity.
