### ISSUE TITLE
Broken Title and Year with TV Series

### ISSUE THREAD

**Issue by Kotaless** [buzz/imdb-link-em-all#65]
Hello. IMDB processing TV Series titles differently. This causing the script to not dedect title and year correctly.

> Movie: https://www.imdb.com/title/tt0117802
> <title>Swingers (1996) - IMDb</title>
>
> IMDB_TITLE=Swingers
> IMDB_YEAR=1996

> TV Series: https://www.imdb.com/title/tt6741278
> <title>Invincible (TV Series 2021– ) - IMDb</title>
>
> IMDB_TITLE=Invincible (TV Series 2021– ) - IMDb
> IMDB_YEAR=undefined

A simple split method fixing the title but the year remains broken. 
Line 449
`  }, encode = true) => str.replace(new RegExp('{{IMDB_TITLE}}', 'g'), encode ? encodeURIComponent(title) : title.split(" (TV Series",1)).replace(new RegExp('{{IMDB_ID}}', 'g'), id).replace(new RegExp('{{IMDB_YEAR}}', 'g'), year);`

Is it possible to fix it completely?

**Comment by buzz** [comment]
See also #8
