### ISSUE TITLE
PrivateHD not available

### ISSUE THREAD

**Issue by MoneyAllDay** [buzz/imdb-link-em-all#66]
Two years ago [PrivateHD](https://privatehd.to/torrents) seems to have been added https://github.com/buzz/imdb-link-em-all/issues/31 but i can't see it on the list, was it removed?

It's possible to search just by the IMDb link but they give each movie/series a unique ID.

I'm not sure if your script can differentiate between movies and tv-shows/series because PrivateHD separates the url but

Search url for movies:

https://privatehd.to/movies?imdb=ttXXXXXXX

Search url for TV shows:

https://privatehd.to/tv-shows?imdb=ttXXXXXXX

**Comment by buzz** [comment]
Please provide full info to add new sites. See [Editing websites](https://github.com/buzz/imdb-link-em-all/wiki/Editing-websites) for details.

Also see #8
