### ISSUE TITLE
RUtracker is pointing at .ORG instead of .NET, which in my region fails

### ISSUE THREAD

**Issue by janaxhell** [buzz/imdb-link-em-all#80]
As of recently I noticed that when I click a RUtracker link from IMDB I land on a "Server down" page. This only happens if the link has rutracker.**org**. If I manually change it to rutracker.**net**, it works. 
Please add a switch to choose variant.

**Comment by buzz** [comment]
rutracker.org is up. This seems to be an issue on your end.
