### ISSUE TITLE
Torrentleech not working

### ISSUE THREAD

**Issue by A7HN** [buzz/imdb-link-em-all#83]
The current noResultsMatcher "No results found" no longer works. I've tried the following locally:

`"Found 0 torrents" 
`
`"Found<br><b>0</b><br>torrents.". `

I also tried experimenting with EL_COUNT. Torrentleech and podnapisi seem to have a similar results page.

Podnapisi.net:
```
<table class="table table-striped table-hover">
      <tbody><tr class="subtitle-entry" data-href="/en/subtitles/en-dune-part-two-2024/2wpI">
```

Torrentleech:
```
<table class="table table-striped table-hover torrents">
	<tbody><tr class="torrent" data-tid="241312895">
```

But while the following works for podnapisi:

`"noResultsMatcher": ["EL_COUNT", "table.table tr.subtitle-entry", "GT", 0],
`

This doesn't work for torrentleech:

`"noResultsMatcher": ["EL_COUNT", "table.table tr.torrent", "GT", 0],`

Any advice on how to get this working?

**Comment by buzz** [comment]
I can't test this as I don't have an account there.

Thus I can only give general directions. Probably the site has changed the result page. The easiest is to  use a string for `noResultsMatcher`. For this to work, look at the result page source. The string has to match exactly against the returned HTML.

- Some pages don't show a message but just an empty table/list. That's what the `EL_COUNT` workaround is for.
- Some pages use [POST requests](https://github.com/buzz/imdb-link-em-all/wiki/POST-requests). That's a different topic. Look at `ofdb` for an example.
- Some dynamic websites use API calls. Then this extension will not be able to retrieve results unfortunately.

Maybe @Kotaless wants to chime in and is able to resolve this (#63).

**Comment by Kotaless** [comment]
Hi. I'm no web dev but have some findings. 
"No results found." text can be seen through developer tools, but if I directly display the page source, it's not there.
I also compared page sources of successful and unsuccessful results and they are identical.
![image](https://github.com/user-attachments/assets/bd16e145-1d8e-434d-bcc9-4c2b620e875b)
![image](https://github.com/user-attachments/assets/fe5bd674-df0e-4fbd-b6dc-a4a952c27fd0)

**Comment by buzz** [comment]
> "No results found." text can be seen through developer tools, but if I directly display the page source, it's not there.
I also compared page sources of successful and unsuccessful results and they are identical.

It's a dynamic website.

> Some dynamic websites use API calls. Then this extension will not be able to retrieve results unfortunately.

This extension merely retrieves static HTML pages, it doesn't execute any site-specific JS or has knowledge about specific APIs (not unless #9 is resolved).

Thanks for digging into this though.
